[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# required for upgrades: https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades?tab=readme-ov-file#before-running
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
optimizer=true
optimizer_runs=200

evm_version = "shanghai" # devnet initial deployment fails with newest version, subsequent deployments work..

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
