name: Code analysis

on:
  workflow_dispatch:
  workflow_call:

jobs:
  code_analyze:
    name: Code analyze
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install Slither
        run: |
          pip install slither-analyzer

      - name: Run Slither
        run: |
          slither .
